/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.74
 * Generated at: 2023-08-25 09:24:25 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.dto.Book;
import java.util.List;
import javax.persistence.Query;
import com.dto.Customer;
import javax.persistence.EntityManager;
import javax.persistence.Persistence;
import javax.persistence.EntityManagerFactory;
import com.dto.Book;
import javax.persistence.Query;
import java.util.List;
import com.dto.Customer;
import javax.persistence.EntityManager;
import javax.persistence.Persistence;
import javax.persistence.EntityManagerFactory;

public final class UserInterface_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.dto.Customer");
    _jspx_imports_classes.add("com.dto.Book");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("javax.persistence.Query");
    _jspx_imports_classes.add("javax.persistence.Persistence");
    _jspx_imports_classes.add("javax.persistence.EntityManagerFactory");
    _jspx_imports_classes.add("javax.persistence.EntityManager");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Main Page</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"Css.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	 ");

	EntityManagerFactory emf=Persistence.createEntityManagerFactory("Booking");
	EntityManager em=emf.createEntityManager();
	
	Customer customer=(Customer)session.getAttribute("customer");
	
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	<div class=\"Search-2\">\r\n");
      out.write("	<h1>Welcome, ");
      out.print(customer.getName() );
      out.write("</h1>\r\n");
      out.write("		<nav style=\"height: 3%;\">\r\n");
      out.write("			<p style=\"padding-left: 60px;width: 100px;\"><a href=\"Cart.jsp\">Cart</a></p>\r\n");
      out.write("			<p><a href=\"History.jsp\">Buying History</a></p>\r\n");
      out.write("		</nav>\r\n");
      out.write("		<form action=\"UserInterface.jsp\">\r\n");
      out.write("			<p>Search Here</p>\r\n");
      out.write("			<input type=\"text\" name=\"name\" placeholder=\"Name of book\">\r\n");
      out.write("			<span>OR</span>\r\n");
      out.write("			<input type=\"text\" name=\"category\" placeholder=\"Category\">\r\n");
      out.write("			<input type=\"submit\" value=\"Search\">\r\n");
      out.write("		</form>\r\n");
      out.write("	</div>\r\n");
      out.write("	");

		String Name=request.getParameter("name");
		String Cat=request.getParameter("category");
		
		if(Name!=null){
			Query qu=em.createQuery("select a from Book a where a.Bname=?1");
			qu.setParameter(1, Name);
			List<Book> book=qu.getResultList();
			
			if(book.size()>0){
				for(Book b:book){
					if(b.getStock()!=0){
				
      out.write("\r\n");
      out.write("			<div>\r\n");
      out.write("				<div class=\"contain\">\r\n");
      out.write("					<h2>Book Name:");
      out.print(b.getBname() );
      out.write("</h2>\r\n");
      out.write("					<p>Publisher Name:");
      out.print(b.getPublisherName() );
      out.write("</p>\r\n");
      out.write("					<p>Writer Name:");
      out.print(b.getWriterName() );
      out.write("</p>\r\n");
      out.write("					<p>Category:");
      out.print(b.getCategory() );
      out.write("</p>\r\n");
      out.write("					<p>Stock:");
      out.print(b.getStock() );
      out.write("</p>\r\n");
      out.write("					<p>Price:");
      out.print(b.getPrice() );
      out.write("</p>\r\n");
      out.write("					<p class=\"anchor\"><a href=\"AddCartCode.jsp?Id=");
      out.print(b.getId());
      out.write("\">Add to Cart</a></p>\r\n");
      out.write("					<p class=\"anchor\"><a href=\"BookCode.jsp?Id=");
      out.print(b.getId());
      out.write("\">Buy Now</a></p>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("				");
 
					}
				}
			}
			else{
				
      out.write("\r\n");
      out.write("				<h2>Sorry No Books Available</h2>\r\n");
      out.write("				");

			}
		}
		else if(Cat!=null){
			Query qu=em.createQuery("select a from Book a where a.Category=?1");
			qu.setParameter(1, Cat);
			List<Book> book=qu.getResultList();
		
		if(book.size()>0){
			for(Book b:book){
				//if(b.getStock()!= 0){
			
      out.write("\r\n");
      out.write("		<div>\r\n");
      out.write("			<div class=\"contain\">\r\n");
      out.write("				<h2>Book Name:");
      out.print(b.getBname() );
      out.write("</h2>\r\n");
      out.write("				<p>Publisher Name:");
      out.print(b.getPublisherName() );
      out.write("</p>\r\n");
      out.write("				<p>Writer Name:");
      out.print(b.getWriterName() );
      out.write("</p>\r\n");
      out.write("				<p>Category:");
      out.print(b.getCategory() );
      out.write("</p>\r\n");
      out.write("				<p>Stock:");
      out.print(b.getStock() );
      out.write("</p>\r\n");
      out.write("				<p>Price:");
      out.print(b.getPrice() );
      out.write("</p>\r\n");
      out.write("				<p class=\"anchor\"><a href=\"AddCartCode.jsp?Id=");
      out.print(b.getId());
      out.write("\">Add to Cart</a></p>\r\n");
      out.write("				<p class=\"anchor\"><a href=\"BookCode.jsp?Id=");
      out.print(b.getId());
      out.write("\">Buy Now</a></p>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("			");
 
				//}
			}
		}
		else{
			
      out.write("\r\n");
      out.write("			<h2>Sorry No Books Available</h2>\r\n");
      out.write("			");

		}
	}
	
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
